### ISSUE TITLE
你好，能否在解包器中增加对结束字符的支持

### ISSUE THREAD

**Issue by chatop2020** [landriesnidis/STTech.BytesIO#1]
有些协议中开始字符串不固定，但结束一般会加个\r\n的结束附，现在只能指定startmask,没有endmask，能否增加一下？

**Comment by landriesnidis** [comment]
Hi, 这是解包器应对三种常见协议类型时的使用方法，希望能对您有帮助。
[C# 优雅处理通信中的粘包和断包（一） 处理固定长的的协议](https://blog.csdn.net/lgj123xj/article/details/125226286)
[C# 优雅处理通信中的粘包和断包（二） 处理非固定长度的协议](https://blog.csdn.net/lgj123xj/article/details/125287745)
[C# 优雅处理通信中的粘包和断包（三） 处理使用结束符的协议](https://blog.csdn.net/lgj123xj/article/details/125324482)

**Comment by chatop2020** [comment]
hi,
如果应用第三种方式，处理使用结束符的协议，，也是需要固定头部的，有些协议头部不固定，可能是AA BB开始，可能是CC DD开始，这样的协议是不是就不能用第三种方式来解了？
目前我碰到一种协议是这样的
固定长度，头部是设备型号，最后以\r\n结束
头部的设备型号可能因为设备批次不一样而变化，这种情况下，现有的方式好像都处理不了。

**Comment by landriesnidis** [comment]
这种情况之前确实没有遇到过，通常开发一个设备的SDK时，协议都是固定的，这种同一个客户端接收不同协议数据包的情况之前并没有考虑过。
但是你可以尝试这样解决：不填写解包器的StartMark，而是在计算方法中去判断当前的包头是AABB还是CCDD，就像示例中判断结尾（EndMark）那样，你可以创建StartMark1，StartMark2...根据不同的头用不用的包长计算规则即可。

**Comment by chatop2020** [comment]
好的，我尝试一下，谢谢。
