### ISSUE TITLE
在事件中处理接收的数据，数据顺序错乱

### ISSUE THREAD

**Issue by LongYuMax** [landriesnidis/STTech.BytesIO#2]
![image](https://user-images.githubusercontent.com/36873363/201009001-1ccd11d6-1228-4c06-9584-74763ecaac1a.png)
当接收连续的大量的数据时，无法保证数据的顺序，也就无法保证数据的可靠性。

**Comment by landriesnidis** [comment]
接收数据一定是顺序的，在BytesIO中每接收到一帧的数据都会依次通过OnDataReceived返回给用户。
截图能看到的代码我没法确定你是如何处理接收到的数据的。
你可以通过QQ群738018341或者通过微信群联系到我，我们再进一步沟通你遇到的这个问题。
![QQ图片20221110135300](https://user-images.githubusercontent.com/17898889/201011739-6d512e40-a8b7-4587-b9d0-a3e0fdbc290c.png)

**Comment by landriesnidis** [comment]
Hi, 您说的这个问题确实存在。
原因是每次接收到一帧的数据包都会启用一个异步任务去回调OnDataReceived事件，当频繁接收数据时会并行触发事件，但执行顺序并不可靠。
之前的测试都是带有协议的通信测试，导致这个问题一直没有被发现。
您提出的这个BUG非常有价值，我们会尽快发布新版本，感谢。
