### ISSUE TITLE
TcpServer存在内存泄漏问题

### ISSUE THREAD

**Issue by zhanghuang515** [landriesnidis/STTech.BytesIO#4]
新建一个TcpServer并开启心跳检测，有固定个数的客户端定期连接、断开，随着时间推移，内存占用越来越大。

**Comment by landriesnidis** [comment]
Hi, 经过测试服务端在启用心跳检测并频繁断开重连后，内存开销确实出现了明显的增加。
最终在心跳检测扩展功能中发现了内存泄漏的BUG。
由于之前应用场景主要集中在上位机开发的方向，大多都是客户端的开发，而单一客户端启用心跳检查后断开重连产生的内存泄漏并没有这么明显，以至于这个一直存在的BUG一直没有被发现。
非常感谢您指出的这个BUG，这对BytesIO来说非常重要。此BUG已在[2.12.8-Beta1124](https://www.nuget.org/packages/STTech.BytesIO.Core/2.12.8-Beta1124)预览版本中得到初步的修复。
