### ISSUE TITLE
6.0作为主程序调用4.8的类库，客户端断开连接服务器无反应，服务器不知道客户端断开连接

### ISSUE THREAD

**Issue by mengjianhu** [landriesnidis/STTech.BytesIO#6]

**Comment by landriesnidis** [comment]
已确认STTech.BytesIO.Tcp.TcpServer类的ClientDisconnected事件在net6.0环境下未触发（客户端主动断开时），我会尽快定位问题并修复。

**Comment by landriesnidis** [comment]
Hi，这个BUG在已经在STTech.BytesIO.Tcp 2.12.10-alpha0510中修复了。还请测试确认是否解决你代码中发生的异常。

![9 ATDDKPV5NG)G1GBR1F HQ](https://github.com/landriesnidis/STTech.BytesIO/assets/17898889/c9967599-b275-4034-be2c-fb783cffa984)
